export const selectors = {
  emailInput: "#email",
  passwordInput: "#password",
  submitButton: "#submit",
  contactListTable: "#myTable",
  contactTableBody: ".contactTableBodyRow",
  addContact: "#add-contact",
  firstName: "#firstName",
  lastName: "#lastName",
  birthDateID: "#birthdate",
  phoneInput: "#phone",
  address: "#street1",
  address1: "#street2",
  cityInput: "#city",
  stateProvince: "#stateProvince",
  postalCodeInput: "#postalCode",
  countryName: "#country",
  cancelButton: "#cancel",
  logoutButton: "#logout",
  editContactButton: "#edit-contact",   
  deleteContactButton: "#delete",
  returnToContactListButton: "#return",
};
